[tool.poetry]
name = "cologne-treemap-api"
version = "0.1.0"
description = "API to request information about city trees in Cologne, Germany"
readme = "README.md"
authors = ["zushicat"]

[tool.poetry.dependencies]
python = "~3.6"

json-rpc = "^1.10.8"
Werkzeug = "^0.15.1"
